### PR TITLE
Modified to remove deprecated endpoints

### PR DESCRIPTION
**Pull request by basmith322**
Adding this PR in order to update the deprecated endpoints for the bitbucket API.

See https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-teams-deprecation/

### CODE REVIEW

**Comment by ShaulTransmit** [comment]
@basmith322 any idea if this repo is still maintained and who can merge this PR?
just encountered this issue as well

**Comment by ShaulTransmit** [comment]
P.S. from what I saw bitbucket seem to have changed `admin` to `owner`
`{"type": "error", "error": {"message": "role must be specified as 'owner', 'collaborator', or 'member'"}}`

**Comment by basmith322** [comment]
Absolutely no idea who if anyone is maintaining this, I opened a PR just to make them aware in case.
That looks like they have also changed contributor to collaborator...

**Comment by ShaulTransmit** [comment]
@mallowlabs this is blocking usage of this plugin due to deprecated endpoint in bitbucket, getting back:
```
Response from bitbucket api https://api.bitbucket.org/2.0/teams/?role=admin
Dec 16, 2021 3:42:10 PM FINEST org.jenkinsci.plugins.api.BitbucketApiService
{"type": "error", "error": {"message": "This endpoint has been removed. See our documentation for more information. https://developer.atlassian.com/cloud/bitbucket/rest/api-group-teams/#api-teams-get"}}
```
please advice how best to progress this

**Comment by basmith322** [comment]
A bit more digging has uncovered the real problems and I have engineered a fix. Need to add some more testing and make some more changes. Going to close this PR and put in a new one with the updated fixes as this one is misleading.

**Pull request closed without merging**
